export const SUPPORTED_LANGUAGES = {
  // Indian Languages
  'hi': { name: 'Hindi', flag: '🇮🇳', code: 'hi-IN' },
  'bn': { name: 'Bengali', flag: '🇮🇳', code: 'bn-IN' },
  'ta': { name: 'Tamil', flag: '🇮🇳', code: 'ta-IN' },
  'te': { name: 'Telugu', flag: '🇮🇳', code: 'te-IN' },
  'mr': { name: 'Marathi', flag: '🇮🇳', code: 'mr-IN' },
  'gu': { name: 'Gujarati', flag: '🇮🇳', code: 'gu-IN' },
  'kn': { name: 'Kannada', flag: '🇮🇳', code: 'kn-IN' },
  'ml': { name: 'Malayalam', flag: '🇮🇳', code: 'ml-IN' },
  'pa': { name: 'Punjabi', flag: '🇮🇳', code: 'pa-IN' },
  'ur': { name: 'Urdu', flag: '🇮🇳', code: 'ur-IN' },
  'or': { name: 'Odia', flag: '🇮🇳', code: 'or-IN' },
  'as': { name: 'Assamese', flag: '🇮🇳', code: 'as-IN' },
  'sa': { name: 'Sanskrit', flag: '🇮🇳', code: 'sa-IN' },
  
  // Global Languages
  'en': { name: 'English', flag: '🇺🇸', code: 'en-US' },
  'es': { name: 'Spanish', flag: '🇪🇸', code: 'es-ES' },
  'fr': { name: 'French', flag: '🇫🇷', code: 'fr-FR' },
  'de': { name: 'German', flag: '🇩🇪', code: 'de-DE' },
  'it': { name: 'Italian', flag: '🇮🇹', code: 'it-IT' },
  'pt': { name: 'Portuguese', flag: '🇵🇹', code: 'pt-PT' },
  'ru': { name: 'Russian', flag: '🇷🇺', code: 'ru-RU' },
  'ja': { name: 'Japanese', flag: '🇯🇵', code: 'ja-JP' },
  'ko': { name: 'Korean', flag: '🇰🇷', code: 'ko-KR' },
  'zh': { name: 'Chinese', flag: '🇨🇳', code: 'zh-CN' },
  'ar': { name: 'Arabic', flag: '🇸🇦', code: 'ar-SA' },
  'th': { name: 'Thai', flag: '🇹🇭', code: 'th-TH' },
  'vi': { name: 'Vietnamese', flag: '🇻🇳', code: 'vi-VN' },
  'nl': { name: 'Dutch', flag: '🇳🇱', code: 'nl-NL' },
  'sv': { name: 'Swedish', flag: '🇸🇪', code: 'sv-SE' },
  'pl': { name: 'Polish', flag: '🇵🇱', code: 'pl-PL' },
  'ro': { name: 'Romanian', flag: '🇷🇴', code: 'ro-RO' },
};
